name: Mirror

on:
  workflow_dispatch:
    inputs:
      git_remote:
        default: 'https://kernel.googlesource.com/pub/scm/linux/kernel/git/rt/linux-stable-rt.git/'
        type: string
      mirror_branches:
        default: 'v5.4-rt,v5.15-rt'
        type: string

# Ensures that only one mirror task will run at a time.
concurrency:
  group: git-mirror

jobs:
  git-mirror:
    runs-on: ubuntu-latest
    steps:
      - name: git mirror branches test
        run: |
          branches_original=${{ github.event.inputs.mirror_branches }}
          branches=(${branches_original//,/ })
          git clone --filter=blob:none -b ${branches[0]} ${{ github.event.inputs.git_remote }} tmp
          cd tmp
          git remote add github https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          for branch in ${branches[@]}; do
            git push github refs/remotes/origin/${branch}:refs/heads/${branch}
          done;

permissions:
  contents: write
  deployments: write
  statuses: read
